# Generated by Django 4.2.13 on 2024-06-12 07:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dibujo', '0003_remove_like_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Precio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
        migrations.AlterField(
            model_name='dibujo',
            name='precio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dibujo.precio'),
        ),
    ]
